name: pocket-js-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=inorbit
    ports:
      - "5432:5432"
